name: TourVerse Backend CI

on:
  push:
    branches: [ main, hari_dev ]
    paths: [ 'backend/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'backend/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: tourverse_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
      
      redis:
        image: redis:6.0
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Create test properties
      run: |
        cd backend
        cp src/main/resources/application.properties src/main/resources/application-test.properties
        echo "spring.datasource.url=jdbc:mysql://localhost:3306/tourverse_test" >> src/main/resources/application-test.properties
        echo "spring.datasource.username=root" >> src/main/resources/application-test.properties
        echo "spring.datasource.password=root123" >> src/main/resources/application-test.properties
        echo "spring.data.mongodb.uri=mongodb://localhost:27017/tourverse_test" >> src/main/resources/application-test.properties
        echo "spring.data.redis.host=localhost" >> src/main/resources/application-test.properties

    - name: Run tests
      run: |
        cd backend
        mvn clean test -Dspring.profiles.active=test

    - name: Generate test report
      run: |
        cd backend
        mvn jacoco:report

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: backend/target/site/jacoco/jacoco.xml
        fail_ci_if_error: false

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build application
      run: |
        cd backend
        mvn clean package -DskipTests

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jar-artifact
        path: backend/target/*.jar
